# should probably build it for real, and pull in libs however is proper, but
# until then, this file will copy in from the libs repository.  This only
# really works when run when both repos are checked out as siblings (i.e. from
# Jenkins)

FROM nginx

COPY popbio-map-libs /usr/share/nginx/html/web/libs
COPY popbio-map/web /usr/share/nginx/html/web

