version: '3.5'

volumes:
  solrdata:         # Store solr cores' data and configs
  logs:

services:
  solr:
    image: veupathdb/solr:${SOLR_TAG:-latest}
    environment:
      - SOLR_JAVA_MEM=${SOLR_JAVA_MEM:--Xms129m -Xmx129m}
      - REPO_ENV=${SOLR_REPO_ENV:-dev}
      - REPO_KEY=${SOLR_REPO_KEY}
      - REPO_HOST=${SOLR_REPO_HOST}
     # mitigation for cve-2021-44228
      - SOLR_OPTS=$SOLR_OPTS -Dlog4j2.formatMsgNoLookups=true
    volumes:
      - solrdata:/var/solr
    entrypoint:
      - bash
      - "-c"
      - "precreate-core vb_ta /opt/solr/server/solr/configsets/vb_ta;
         precreate-core vb_popbio /opt/solr/server/solr/configsets/vb_popbio;
         exec solr -f"

    networks:
      - internal
      - traefik

    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.${ROUTER:-mapveu-dev}.rule=Host(`solr-${DOMAIN:-mapveu-dev.local.apidb.org}`)"
      - "traefik.http.routers.${ROUTER:-mapveu-dev}.tls=true"
      - "traefik.http.routers.${ROUTER:-mapveu-dev}.entrypoints=local"
      - "com.centurylinklabs.watchtower.enable=${SOLR_WATCHTOWER:-false}"

  web:
    image: veupathdb/popbio-map:${WEB_TAG:-latest}

    networks:
      - internal
      - traefik

    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.map-${ROUTER:-mapveu-dev}.rule=Host(`${DOMAIN:-mapveu-dev.local.apidb.org}`)"
      - "traefik.http.routers.map-${ROUTER:-mapveu-dev}.tls=true"
      - "traefik.http.routers.map-${ROUTER:-mapveu-dev}.entrypoints=local"
      - "com.centurylinklabs.watchtower.enable=${WEB_WATCHTOWER:-false}"

  proxy:
    image: veupathdb/solr-proxy:${PROXY_TAG:-latest}
    environment:
      - SOLR_HOST=${SOLR_HOST:-solr}
      - SOLR_PORT=${SOLR_PORT:-8983}
      - LISTEN_PORT=${LISTEN_PORT:-8000}

    volumes:
      - logs:/home/node/logs
    networks:
      - internal
      - traefik

    labels:
      - "traefik.docker.network=traefik"
      - "traefik.http.services.secproxy-${ROUTER:-mapveu-dev}.loadbalancer.server.port=9090"
      - "traefik.http.services.csvproxy-${ROUTER:-mapveu-dev}.loadbalancer.server.port=8000"

      - "traefik.http.routers.secproxy-${ROUTER:-mapveu-dev}.service=secproxy-${ROUTER:-mapveu-dev}"
      - "traefik.http.routers.secproxy-${ROUTER:-mapveu-dev}.rule=Host(`${DOMAIN:-mapveu-dev.local.apidb.org}`)&&PathPrefix(`/web/asolr`)"

      - "traefik.http.middlewares.strip-asolr.stripprefix.prefixes=/web/asolr"
      - "traefik.http.middlewares.strip-asolr.stripprefix.forceslash=false"
      - "traefik.http.routers.secproxy-${ROUTER:-mapveu-dev}.middlewares=strip-asolr"

      - "traefik.http.routers.secproxy-${ROUTER:-mapveu-dev}.tls=true"
      - "traefik.http.routers.secproxy-${ROUTER:-mapveu-dev}.entrypoints=local"

      - "traefik.http.routers.csvproxy-${ROUTER:-mapveu-dev}.service=csvproxy-${ROUTER:-mapveu-dev}"
      - "traefik.http.routers.csvproxy-${ROUTER:-mapveu-dev}.rule=Host(`${DOMAIN:-mapveu-dev.local.apidb.org}`)&&PathPrefix(`/web/esolr`)"
      - "traefik.http.routers.csvproxy-${ROUTER:-mapveu-dev}.tls=true"
      - "traefik.http.routers.csvproxy-${ROUTER:-mapveu-dev}.entrypoints=local"

      - "traefik.http.middlewares.strip-esolr.stripprefix.prefixes=/web/esolr"
      - "traefik.http.middlewares.strip-esolr.stripprefix.forceslash=false"
      - "traefik.http.routers.csvproxy-${ROUTER:-mapveu-dev}.middlewares=strip-esolr"
      - "com.centurylinklabs.watchtower.enable=${PROXY_WATCHTOWER:-false}"

networks:
  internal: # internal network
    external: false
  traefik: # external network
    external: true

